### ISSUE TITLE
Potential Bug of Wrong Slack Notification

### ISSUE THREAD

**Issue by faisaltheparttimecoder** [malshoff/Slack-Status-Bot#1]
There is a possibility of a bug over here

https://github.com/malshoff/Slack-Status-Bot/blob/master/roster.py#L37

**The scenario**

+ Engineer make himself on training
+ The code works perfectly
+ He later changes his mind and updates the schedule to "Available"
+ The roster will show two entry ( One Training & Other available ) and the current code will warn irrespective if the user has removed him out of training.

**Solution**

Filter the schedule further using **active = True**, this will ensure that only the valid schedule is returned rather than history of schedules for that specific date.

You can find all the filtering option of the API here

http://pivotal-roster-api.cfapps.io/apidocs/#operation/api_schedule_employee_schedule_list

Btw great job on the bot :)

**Comment by malshoff** [comment]
Hey Faisal! Thanks for pointing that out, funnily enough that scenario played out yesterday when 2 engineers switched training days. Thanks for that filter tip.
